spring.application.name=bestlogspractices
server.port=2917

spring.datasource.url=jdbc:postgresql://localhost:5433/audit_local
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update